### ISSUE TITLE
Interfacing Stepper motor with Beaglebone Black Wireless

### ISSUE THREAD

**Issue by joyalraju** [joyalraju/Capstone-Project-Summer-2020#12]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connecting an stepper motor to a BBB Wirelss in terms of Hardware and Software?

**Comment by joyalraju** [comment]
A separate power supply is essential to connect the common terminal of the ULN2003 driver module in order to avoid high current draw from beaglebone black wireless for safe working. It should have a common ground bus with beaglebone, power supply, and ULN2003 for smooth working. A delay of minimum of 2 ms should be added in the code after enabling each coil to get it energized.
