### ISSUE TITLE
Interfacing GPS module with Beaglebone Black Wireless

### ISSUE THREAD

**Issue by joyalraju** [joyalraju/Capstone-Project-Summer-2020#14]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of a GPS Module to a BBB Wireless in terms of Hardware and software?
2. How do you resolve them?

**Comment by joyalraju** [comment]
1. main issue is with the accuracy of the system. Though the manufacture says the accuracy of 1.8 meters, the user doesn't get that much accuracy in location. The next issue is with the fix (the active connection between the satellite and receiver) we have to wait to get the fix. Another issue was for the beaglebone black wireless UART port should be enabled to communicate with the GPS module.
2. By adding an external antenna with the GPS module can resolve the problem with accuracy. Using the command "config-pin <pin number> uart" will enable the UART pin to solve the next issue.
