### ISSUE TITLE
Interfacing ThingSpeak with Beaglebone Black Wireless

### ISSUE THREAD

**Issue by joyalraju** [joyalraju/Capstone-Project-Summer-2020#15]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with interfacing the BBB to the ThingSpeak?
2. How did you resolve them?
3. How to decrease the delay from ThingSpeak? Does change of the MCU work?

**Comment by joyalraju** [comment]
1. main issue is the user cannot update all fields at a time, sstream is not available in c code which is the main string structure for sending data to the cloud.
2.  delay of 15 seconds is required between updating each field to avoid overlapping or missing updates of each field. CPP code can incorporate the sstream and is effective.
3. paid version of thingspeak will be effective to reduce the delay. Delay is independent of MCU, this delay is with thingspeak server(time to update the server).
